### ISSUE TITLE
Problem with sending voice through ffmpeg(spamming Sent Speaking)

### ISSUE THREAD

**Issue by lofour** [RogueException/Discord.Net#1274]
Im sending audio using ffmpeg(`ffmpeg version N-93129-g9e1e521393`) and Discord.Net(`Discord.Net 2.0.2-dev-01059`).
I'm sending audio from local .mp3 using ffmpeg with methods like below.
When i'm sending first time from connection to voice channel - it is all ok.
For the next times bot spamming Sent Speaking and his "circle" in discord is blinking.
```cs
private Process CreateStream(string path)
{
	return Process.Start(new ProcessStartInfo
	{
		FileName = "ffmpeg",
		Arguments = $"-hide_banner -loglevel panic -i \"{path}\" -ac 2 -f s16le -ar 48000 pipe:1",
		UseShellExecute = false,
		RedirectStandardOutput = true,
	});
}
```
```cs
using (var ffmpeg = CreateStream(path))
using (var output = ffmpeg.StandardOutput.BaseStream)
using (var discord = AudioClient.CreatePCMStream(AudioApplication.Mixed))
{
	try
	{
		IsSending = true;
		await AudioClient.SetSpeakingAsync(true);//just try to fix
		await output.CopyToAsync(discord, _token);//_token to stop sending audio
		return true;
	}
	catch (OperationCanceledException)
	{
		return true;
	}
	finally
	{
		await discord.FlushAsync();
		await AudioClient.SetSpeakingAsync(false);//just try to fix
		IsSending = false;
	}
}
```

**Comment by alovegit** [comment]
I have this issue as well.  To work around it, I had to create the PCM stream once and re-use it every time.  That's the only solution I've found until this gets resolved.

**Comment by F0903** [comment]
Same issue. Will try the solution above.

**Comment by SubZero0** [comment]
Took some time but should be fixed by #1667

**Comment by mcpro777** [comment]
> I have this issue as well. To work around it, I had to create the PCM stream once and re-use it every time. That's the only solution I've found until this gets resolved.

I can confirm this is still an issue.  Thank you for posting this.  It fixed my problem.

**Comment by jinwoo-lee-github** [comment]
still have problem.
